source 'https://github.com/CocoaPods/Specs.git'

target 'MKCommons', :exclusive => true do
  pod "MKCommons", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MKCommons", :path => "../"

  
end
